production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: framgia-jobs
  pool: 5
  username: root
  password: <%=ENV["FRAMGIA_JOBS_DB_PASSWORD"]%>
  socket: /var/run/mysqld/mysqld.sock